version: "2"
services:
  agent:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - GTM_AGENT_PORT=${GTM_AGENT_PORT}
      - GTM_AGENT_AWS_ACCESS_KEY_ID=${GTM_AGENT_AWS_ACCESS_KEY_ID}
      - GTM_AGENT_AWS_SECRET_ACCESS_KEY=${GTM_AGENT_AWS_SECRET_ACCESS_KEY}
      - GTM_AWS_REGION=${GTM_AWS_REGION}
      - GTM_SQS_PENDING_QUEUE=${GTM_SQS_PENDING_QUEUE}
      - GTM_SQS_RESULTS_QUEUE=${GTM_SQS_RESULTS_QUEUE}
      - GTM_SNS_RESULTS_TOPIC=${GTM_SNS_RESULTS_TOPIC}
      - GTM_TASK_CONFIG_FILENAME=${GTM_TASK_CONFIG_FILENAME}
      - GTM_AGENT_GROUP=${GTM_AGENT_GROUP}
      - GTM_GITHUB_TOKEN=${GTM_GITHUB_TOKEN}
      - GTM_GITHUB_WEBHOOK_SECRET=${GTM_GITHUB_WEBHOOK_SECRET}
      - GTM_GITHUB_HOST=${GTM_GITHUB_HOST}
      - GTM_GITHUB_HOST=${GTM_GITHUB_HOST}
      - GTM_GITHUB_DEBUG=${GTM_GITHUB_DEBUG}
      - GTM_GITHUB_TIMEOUT=${GTM_GITHUB_TIMEOUT}
      - GTM_GITHUB_PATH_PREFIX=${GTM_GITHUB_PATH_PREFIX}
      - GTM_GITHUB_PROXY=${GTM_GITHUB_PROXY}
      - GTM_GITHUB_OWNER=${GTM_GITHUB_OWNER}
    volumes:
      - ./:/home/node/app
    ports:
      - "${GTM_AGENT_PORT}:${GTM_AGENT_PORT}"
    command: "npm run agent"

